# Generated by Django 5.1.2 on 2024-11-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='{% get_media_prefix %}login.jpg', null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
