# Generated by Django 5.1.2 on 2024-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='media/login.png', null=True, upload_to='fotos/'),
        ),
    ]
