# Generated by Django 5.1.2 on 2024-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuarios_foto_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
