# Generated by Django 5.1.2 on 2024-11-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=15, unique=True),
        ),
    ]
