# Generated by Django 5.1.2 on 2024-12-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_fundacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tecnicos/')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='presidentes/')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jogadores/')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estadios/')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.time')),
            ],
        ),
    ]
