# Generated by Django 5.1.2 on 2024-12-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trendfeeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interacaousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticias',
            name='categorias',
            field=models.ManyToManyField(related_name='noticias', through='trendfeeds.CategoriaNoticias', to='trendfeeds.categoria'),
        ),
        migrations.AddField(
            model_name='interacaousuario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias'),
        ),
        migrations.AddField(
            model_name='categorianoticias',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias'),
        ),
        migrations.AddField(
            model_name='timefavorito',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.categoria'),
        ),
        migrations.AddField(
            model_name='timefavorito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interacaousuario',
            unique_together={('usuario', 'noticia')},
        ),
    ]
