# Generated by Django 5.1.2 on 2024-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='serie',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
