# Generated by Django 5.1.2 on 2024-11-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0002_categorianoticias_noticias_interacaousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trendfeeds.categorianoticias'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='link',
            field=models.URLField(default='https://ge.globo.com/'),
        ),
    ]
