# Generated by Django 5.1.2 on 2024-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='serie',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
