# Generated by Django 5.1.2 on 2024-11-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(default='outro', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorianoticias',
            name='nomecategoria',
        ),
        migrations.RemoveField(
            model_name='interacaousuario',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='interacaousuario',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='noticias',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categorianoticias',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias'),
        ),
        migrations.AddField(
            model_name='interacaousuario',
            name='comentario',
            field=models.TextField(blank=True, max_length=7000),
        ),
        migrations.AddField(
            model_name='interacaousuario',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noticias',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='categorianoticias',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.categoria'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='categorias',
            field=models.ManyToManyField(related_name='noticias', through='trendfeeds.CategoriaNoticias', to='trendfeeds.categoria'),
        ),
        migrations.DeleteModel(
            name='ImagemNoticias',
        ),
    ]
