# Generated by Django 5.1.2 on 2024-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0003_noticias_categoria_noticias_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
