# Generated by Django 5.1.2 on 2024-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0003_alter_categoria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
