# Generated by Django 5.1.2 on 2024-11-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0003_categoria_remove_categorianoticias_nomecategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorianoticias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.categoria'),
        ),
        migrations.AlterField(
            model_name='categorianoticias',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
