# Generated by Django 5.1.2 on 2024-11-18 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0003_categoria_remove_categorianoticias_nomecategoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interacaousuario',
            constraint=models.UniqueConstraint(fields=('noticia', 'usuario'), name='unique_interaction'),
        ),
    ]
