# Generated by Django 5.1.2 on 2024-11-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0004_noticias_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
