# Generated by Django 5.1.2 on 2024-11-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0004_alter_categorianoticias_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorianoticias',
            name='destaque',
        ),
    ]
