# Generated by Django 5.1.2 on 2024-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0004_alter_categoria_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='titulo_bonito',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
