# Generated by Django 5.1.2 on 2024-11-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0005_alter_noticias_slug_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemnoticias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
