# Generated by Django 5.1.2 on 2024-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0005_noticias_titulo_bonito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo_bonito',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
