# Generated by Django 5.1.2 on 2024-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0005_alter_noticias_slug_alter_noticias_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemnoticias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='./trendfeeds/media/'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
