# Generated by Django 5.1.2 on 2024-11-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0005_remove_categorianoticias_destaque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nomecategoria',
            new_name='nome_categoria',
        ),
    ]
