# Generated by Django 5.1.2 on 2024-11-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0006_rename_nomecategoria_categoria_nome_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interacaousuario',
            old_name='texto',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='interacaousuario',
            name='tipo',
        ),
    ]
