# Generated by Django 5.1.2 on 2024-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0006_alter_noticias_titulo_bonito'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='hora_publicacao',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
