# Generated by Django 5.1.2 on 2024-11-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0006_rename_nomecategoria_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='serie',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InteracaoUsuario',
        ),
    ]
