# Generated by Django 5.1.2 on 2024-11-18 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0007_categoria_cor_categoria_descricao_categoria_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timefavorito',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.categoria'),
        ),
        migrations.CreateModel(
            name='InteracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendfeeds.noticias')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
