# Generated by Django 5.1.2 on 2024-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0007_rename_texto_interacaousuario_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacaousuario',
            name='comentario',
            field=models.CharField(blank=True, max_length=7000),
        ),
    ]
