# Generated by Django 5.1.2 on 2024-11-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0008_alter_interacaousuario_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacaousuario',
            name='like',
            field=models.IntegerField(choices=[(1, 'Like'), (0, 'None')], default=0),
        ),
        migrations.AlterField(
            model_name='interacaousuario',
            name='comentario',
            field=models.TextField(blank=True, max_length=7000),
        ),
    ]
