# Generated by Django 5.1.2 on 2024-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendfeeds', '0009_interacaousuario_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaousuario',
            name='like',
        ),
        migrations.AddField(
            model_name='noticias',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
